defaults: &defaults
  adapter: postgresql
  host: localhost
  port: 5432
  username: activebilling
  password: 'password'
  timeout: 10000

production:
  <<: *defaults

test:
  database: openbeer_test
  <<: *defaults

development:
  database: openbeer_development
  <<: *defaults
