# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41c3745c191d03a812a69dcf56a099b04c236f8676a754e077ca52253e6d46853d9f41460152633d740f4c16a6e1bac19e71e3dec7d120b6b6eb80b92c27dff0

test:
  secret_key_base: 0c6812914313739d7e7a0899b2ba8d90793d77885563a2669707fe940ab16e0964a930eb3786b3cb7d82b5d408275836564064d724be50578c5e0e20c4e6b8e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
